pkg/requirements.pip

Unpin python-dateutil since is no longer a problem.
Pin python-daemon since latest version (2.0.3 as today) fails to get
installed wich causes problems with the bundle and the bootstrapper
script.

Pin/unpin dependencies.

---

src/leap/bitmask/config/tests/test_providerconfig.py
src/leap/bitmask/crypto/tests/test_srpauth.py
src/leap/bitmask/provider/providerbootstrapper.py
src/leap/bitmask/provider/tests/test_providerbootstrapper.py
src/leap/bitmask/services/eip/eipbootstrapper.py
src/leap/bitmask/services/eip/eipconfig.py

Remove srpauth obsolete tests.
Remove providerconfig obsolete test.
Set as mandatory the signaler object on ProviderBootstrapper and
EIPBootstrapper.
Closes #6631.

Fix failing tests.

---

src/leap/bitmask/services/soledad/soledadbootstrapper.py

the set_proxies_cb function in backend/components expects to have access
to these public properties.

Re-add public properties removed in previous commit

---

docs/leap-commit-template
docs/leap-commit-template.README

Hopefully this will make our git log more informative.
- Releases: 0.9.0

[docs] Add git commit template and instructions

---

changes/bug_6759_fix_user_id
src/leap/bitmask/gui/mainwindow.py
src/leap/bitmask/services/mail/smtpbootstrapper.py

At some moment, the semantics of the username that we pick from the
login widget changed, so that there's a duplication of the domain part
in the full_user_id that we were passing to the keymanager and the mail
services.
This fix has already been done in the current develop branch (for next
release 0.9.0), so there's no need to port it when merging it back.
While it is true that there's no official release of the client supporting
mail yet, this was an easy fix to port so we will do a 0.8.2
bugfix release so that the 0.8 branch can be used experimentally to test
against development providers. This doesn't mean that you can expect
support on the 0.8.x branch yet, it's only that there is one less bug in
here :)
Resolves: #6759
Releases: 0.8.2

[bug] fix concatenation of full_user_id to make mail work

---

changes/bug-6418_re-enable-providers-list-on-check-failure
src/leap/bitmask/gui/wizard.py

After a provider fails to pass the checks, the providers combo box is
not enabled when it should, we just took care of the provider line edit.
Resolves: #6418

[bug] enable providers combo box on check fail

---

changes/bug-6682_failure-to-unlock-keyring-freezes-bitmask
src/leap/bitmask/gui/login.py

Catch the `keyring.errors.InitError` exception.
The automatic login sequence now stops correctly instead of freezing if
the user cancel the keyring open operation.
- Resolves: #6682

[bug] handle user cancel keyring open operation

---

changes/bug_fix-bitmask-autostart
src/leap/bitmask/frontend_app.py
src/leap/bitmask/gui/mainwindow.py

If the `quit()` call is triggered by the system logout we should not disable
the autostart. Otherwise bitmask won't autostart on the next session
start.
- Resolves: #6424

[bug] do not disable autostart on system quit()

---

changes/bug-6894_change-ip-command-location
pkg/linux/bitmask-root

Change the `ip` command location to support Fedora/RHEL distros.
`/bin/ip` is pressent on Debian/Ubuntu but not on Fedora.
`/sbin/ip` is a symlink to `/bin/ip` on Debian/Ubuntu and a binary on Fedora.
- Resolves: #6894

[bug] change the ip command location to /sbin/

---

changes/bug-syncing_retry
src/leap/bitmask/services/soledad/soledadbootstrapper.py

* Don't check if soledad is still syncing for timeout, it seems that if
it fails it might not have the flag still unset. Check instead if the
callback deferred has being called.
* Count retries properly.
I still have to test it more, and maybe we should not check the deferred but fix soledad syncing flag.

[bug] two small soledad sync issues

---

src/leap/bitmask/app.py
src/leap/bitmask/backend/components.py
src/leap/bitmask/backend_app.py

If the events server is initialized in a different process than the backend,
the txzmq socket raises an "zmq.error.ZMQError: Interrupted system call"
exception during the events server initialization. Despite that, communication
seems to work flawlessly after the initialization.
Moving the events server initialization to the same process as the backend
causes the exception to not be raised during events server intialization.

[bug] move events server init to backend

---

src/leap/bitmask/platform_init/initializers.py

Polkit was being launched and detected correctly, but Bitmask didn't
propagate this result to upper layers, so mainwindow thought the
platform wasn't initialized and then quitted without explanation.
Tested on debian testing, on June 5th 2015, using i3 window manager.
- Resolves: #6652

bug regression: polkit agent is not automatically launched #6652

---

changes/bug_7093-fix-controller-attribute-error
src/leap/bitmask/services/mail/conductor.py

due to remaining bits that had not been changed after a refactor.
- Resolves: #7093

[bug] fix attribute error on mail conductor

---

pkg/requirements.pip

This dependency was previously installed through soledad, but it
doesn't use that lib anymore.

[pkg] add missing taskthread dependency

---

changes/bug-7126_ensure-server-breaks
src/leap/bitmask/backend_app.py

We don't need to run the event server on the backend if we are running
from the standalone bundle since the launcher takes care of that.
- Related: #7126

[bug] don't run event server on the standalone

---

changes/feature-7162_log_lsb_release_info
src/leap/bitmask/app.py

if the lsb_release utility is present on system, log part of its output
so we can have more information about the platform bitmask is running
on.
- Resolves: #7162
- Releases: 0.9.0

[feat] log lsb_release info if available

---

src/leap/bitmask/logs/utils.py

The logger is the first thing to be created and on a first run the
config path won't exist. This way we make sure the path always exists.

[bug] make sure log path exists

---

changes/bug-7185_log-contains-exported-pgp-private-key
src/leap/bitmask/logs/log_silencer.py

Due to #7139 (the logbook log centralizer) logs from 3rd party libs are
included in the centralized logs with lots of debug information and we
don't want that.
We use the existing silencer to exclude logs that are not from leap
modules.
- Resolves: #7185

[bug] log contains exported PGP private key

---

changes/bug-7222_run-background-zmq-subscriber
src/leap/bitmask/gui/logwindow.py
src/leap/bitmask/gui/mainwindow.py
src/leap/bitmask/logs/utils.py

Prevent locks caused by the zmq log handler reaching the zmq's HWM (High
water mark / buffer limit) and causing some components to block until
the buffer is empty (running the zmq handler for instance).
We run the zmq handler in the background all the time to prevent this.
- Resolves: #7222

[bug] run zmq log subscriber in background

---

src/leap/bitmask/util/leap_argparse.py

Is useful for new providers to be able to use the stable Bitmask
version with this flag to be able to use custom certificates.
* Resolves: #7250

[feat] enable '--danger' for stable versions

---

Makefile

Those files are no longer needed (nor present on the repo).
- Resolves: #7384

[bug] copy for cryptography files not needed

---

changes/bug-7281_support-no-locations-for-eip
src/leap/bitmask/backend/components.py
src/leap/bitmask/services/eip/eipconfig.py

Is valid for a provider not to provide locations for their gateways.
- Resolves: #7281

[bug] handle eip-config not providing locations

---

changes/bug-6594_handle-disabled-registration
src/leap/bitmask/backend/api.py
src/leap/bitmask/backend/leapsignaler.py
src/leap/bitmask/config/providerconfig.py
src/leap/bitmask/crypto/srpregister.py
src/leap/bitmask/gui/wizard.py

If the user wants to register a new account we check whether the
provider allows registration or not right after getting the
`provider.json` file and show an error msg on the wizard if not allowed.
Also, there is a new signal to handle the error raised by the server if
a registration attempt is made but is rejected with error `403`.
- Resolves: #6594

[bug] handle disabled registration, error 403.

---

changes/feature-7419_load-credentials-from-env
src/leap/bitmask/gui/mainwindow.py

Look for file defined in the `BITMASK_CREDENTIALS` env variable and load
`provider`, `username` and `password` data.
Trigger login if they were loaded correctly.
The credentials file should look like this:
```
[Credentials]
username = my-account@my-provider.com
password = secret
```
- Resolves: #7419

[feat] load credentials from environment variables

---

src/leap/bitmask/logs/safezmqhandler.py

for the version in ubuntu trusty, the call for the zeromq handler
initialization gets one less argument

[bug] add compatibility for logbook versions < 0.7.0

---

docker/Dockerfile
docker/leap_bootstrap.sh

This is needed if we use wheels, since the zmq library is not build as it is when we install from code.

[pkg] add libzmq dependency

---

src/leap/bitmask/logs/safezmqhandler.py

we need the 'multi' feature all the same, so we'll be depending on
logbook >= 0.7.0.

[pkg] revert attempt to be compatible with logbook 0.6.0

---

pkg/requirements.pip

For our logging we need a new logbook feature that was added on 0.7.0.
- Resolves: #7449

[pkg] require Logbook 0.7.0 or newer

---

changes/bug_7470_fix-service-enabled-method
src/leap/bitmask/gui/account.py
src/leap/bitmask/gui/passwordwindow.py

this was returning None, and therefore breaking soledad password change
(since it checks whether mail is enabled before changing soledad pass
after srp pass change).
- Resolves: #7470

[bug] correctly return expected value

---

changes/bug-7474_handle-soledad-ready-properly
src/leap/bitmask/gui/app.py
src/leap/bitmask/gui/mainwindow.py
src/leap/bitmask/gui/passwordwindow.py
src/leap/bitmask/gui/preferenceswindow.py

Connecting to the `soledad_bootstrap_finished` signal is not enough
since the password change window is created after the signal is emitted,
that way we were not able to tell when soledad is ready to be used.
- Resolves: #7474

[bug] track soledad ready state on a shared place

---

changes/bug-logbook_handler_bubble
src/leap/bitmask/logs/utils.py

NullHandler doesn't have anymore the argument bubble.
https://pythonhosted.org/Logbook/changelog.html#version-0-11-0

[bug] remove bubble argument from the logbook NullHandler

---

changes/bug-7451_missing-attribute
src/leap/bitmask/services/soledad/soledadbootstrapper.py

When the error happens too quickly, the errback is called before the
assign of the callLater. And in the errback we cancel that call which
gives an error.
- Related: #7451

[bug] move assign to prevent race condition

---

changes/next-changelog.rst
src/leap/bitmask/services/soledad/soledadbootstrapper.py

from debian stretch on, gpg will be a symlink to gpg2.
this is currently failing if one uses dpkg-divert to make gpg2 provide
/usr/bin/gpg.
this solution just attempts to use gpg2 binary if the search for gpg
binary fails.
- Resolves: #7563
- Releases: 0.9.1

[bug] use gpg2 binary if gpg not found. Closes: #7563

---

changes/next-changelog.rst
src/leap/bitmask/gui/ui/mail_status.ui

Changed text to what mcnair suggested on issue 7552 and added a small margin above the box to have some separation between the sync/mail status and the instructions message.
- Related: #7552

[feat] improve msg and add margin above box

---

docker/debian/apt-bitmask.sh

Also map 'sana' (codename for kali linux 2.0) to jessie.

[feat] use bitmask repo instead of leap.se

---

src/leap/bitmask/app.py

the original implementation causes problems in win32 (Related #7240) possibly because pyinstaller cannot resolve the lambda correctly. using the documented multiprocessing.Process approach to pass parameters works here

[bug] change backend process spawn method

---

src/leap/bitmask/app.py

according to [1] the backend should raise a Runtime Error, instead what happens is that the process is spawned again and again but never runs actual code. 
[1] https://docs.python.org/2.7/library/multiprocessing.html#multiprocessing.freeze_support

[bug] frozen backend fails to spawn on windows

---

src/leap/bitmask/backend/components.py
src/leap/bitmask/gui/mainwindow.py

This greatly simplifies the handling of the password in the thunderbird
extension.
- Related: #6041

[feat] use same token for imap/smtp authentication

---

src/leap/bitmask/services/mail/imap.py

The failure was processed in start_incoming_mail_service what will make
it return a None when an IncomingMail object was expected. If we
propagate the failure it can be treated properly by the IMAPController.
- Related: #8051

[bug] let the failure propagate
