src/leap/bitmask/services/mail/imapcontroller.py

factory.do_Stop will handle this now.

do not terminate the session on the backend, moved to mail

---

src/leap/bitmask/backend/components.py
src/leap/bitmask/services/soledad/soledadbootstrapper.py

Do the soledad sync the twisted way

---

changes/non-curve-zmq
src/leap/bitmask/backend/backend.py
src/leap/bitmask/backend/backend_proxy.py
src/leap/bitmask/backend/signaler.py
src/leap/bitmask/backend/signaler_qt.py
src/leap/bitmask/backend/utils.py
src/leap/bitmask/backend_app.py
src/leap/bitmask/config/flags.py

Fall back to plain ZMQ if Curve is not available.

---

changes/feature-6713_add-support-for-xfce-polkit
src/leap/bitmask/util/privilege_policies.py

[feat] add support for xfce-polkit agent

---

changes/feature-5526_make-check-button-selected
src/leap/bitmask/gui/ui/wizard.ui
src/leap/bitmask/gui/wizard.py

Also set text to 'bold' so it's easier to find at a first sight.
- Resolves: #5526

[feat] make 'check' button selected by default

---

src/leap/bitmask/app.py

- Resolves: #6426
- Resolves: #6681

[bug] enable atexit subprocess termination

---

changes/feature_update-api-port-pinned-riseup
src/leap/bitmask/provider/pinned_riseup.py

[feat] update api port for pinned riseup

---

changes/VERSION_COMPAT
changes/feature_adapt-to-new-events-on-common
pkg/requirements.pip
src/leap/bitmask/app.py
src/leap/bitmask/crypto/srpauth.py
src/leap/bitmask/gui/mail_status.py
src/leap/bitmask/gui/mainwindow.py
src/leap/bitmask/platform_init/locks.py
src/leap/bitmask/services/mail/conductor.py

**DO NOT MERGE YET**
These are the changes needed to use the new events api on `leap.common` waiting to be merged on https://github.com/leapcode/leap_pycommon/pull/95
- Related: #6359

[feat] adapt to new events api on common

---

src/leap/bitmask/services/soledad/soledadbootstrapper.py

[style] fix typo

---

changes/feature-7342_apply_updates
pkg/tuf/apply_updates.py

apply_updates.py applies the already downloaded files from the updates
folder and removes all the obsolete files from the bundle. It's meant
to be use by the pyinstaller bundle.
- Resolves: #7342
- Related: #5876

[feat] Add script apply_updates.py for pyinstaller bundle

---

changes/bug-7415_fix-arguments-on-raise-window-event
src/leap/bitmask/gui/mainwindow.py

[bug] fix argument number on window raise event

---

changes/bug-fix-logout-auth
changes/bug_7448-fix-logout-auth
src/leap/bitmask/crypto/srpauth.py
src/leap/bitmask/services/mail/imapcontroller.py

logout calls were not being authenticated, so we were receiving 401
return code.

[bug] authenticate logout calls to api

---

changes/feature-7414_remove-taskthread-dependency
pkg/requirements.pip
src/leap/bitmask/backend/backend_proxy.py

Refactor ivan's code (aa4b684d0682ff9faf1577653fa5ceabbc6e0f20) to remove the
time.sleep.
Superseeds #888
- Resolves: #7414

[feat] remove taskthread dependency

---

changes/bug-7453_sync-completed-vs-unread-emails
src/leap/bitmask/gui/mail_status.py

Right after a complete sync we show the unread emails.
- Resolves: #7453

[bug] show unread emails after sync complete

---

changes/feature_4284-download-smtp-certs
src/leap/bitmask/crypto/certs.py
src/leap/bitmask/services/mail/smtpbootstrapper.py
src/leap/bitmask/services/mail/smtpconfig.py

this is ready, but it needs complete testing.
it currently needs platform:develop, which is deployed in dev.bm

[feature] retrieve specific smtp certificate. Closes: #4284

---

CONTRIBUTING.rst
README.rst

[docs] add contributing file

---

changes/bug-7503_handle-soledad-init-fail
src/leap/bitmask/services/soledad/soledadbootstrapper.py

[bug] signal soledad bootstrap fail on init

---

docs/dev/internationalization.rst

In some cases setting just `LANG` doesn't change the language, in those
cases, setting `LC_ALL` does the trick.

[i18n] add an extra env variable to change lang

---

release-notes.rst

Add changes to comply with mcnair's proposed changes.

[docs] reword release notes

---

changes/feature-7552_mail-help-message-on-ui
src/leap/bitmask/gui/mail_status.py
src/leap/bitmask/gui/ui/mail_status.ui

Add a UI message for the user to know where to go next.
This message goes away after 60 seconds or right after a MUA logs in.
- Resolves: #7552

[feat] add ui message to help new mail users

---

changes/next-changelog.rst
src/leap/bitmask/services/mail/conductor.py

[bug] fix typo on signal name

---

changes/next-changelog.rst
src/leap/bitmask/gui/ui/mail_status.ui

[bug] open email help link on browser

---

changes/next-changelog.rst
src/leap/bitmask/services/soledad/soledadbootstrapper.py

[but] Fix errback on InvalidAuthToken

---

src/leap/bitmask/backend/components.py
src/leap/bitmask/gui/advanced_key_management.py

Related to https://github.com/leapcode/keymanager/pull/94

[feat] use fingerprint instead of key_id to address keys

---

Makefile
pkg/linux/bitmask-launcher

[bug] workaround for incompatible qt library in ubuntu

---

changes/next-changelog.rst
src/leap/bitmask/backend/components.py

The thunderbird plugin will read the tokens from there.
- Related: #6041

[feat] Write service tokens to a file

---

src/leap/bitmask/backend/components.py
src/leap/bitmask/gui/preferences_email_page.py
src/leap/bitmask/gui/ui/preferences_email_page.ui

Needs https://github.com/leapcode/keymanager/pull/105

[bug] represent keys correctly in preference window

---

src/leap/bitmask/gui/qt_browser.py

- Resolves: #8069
- Releases: 0.9.2

[feature] enable to download attachments from within webkit
